[[spring-boot-support]]
= Spring Boot support
:sectnums:
:dimensional: true

WARNING: Spring Boot 1.5.x and Micrometer releases (up to Micrometer 1.3.x) that include the `micrometer-spring-legacy` module are now out of support.
Please upgrade to supported releases of Spring Boot and Micrometer.
See the latest https://docs.spring.io/spring-boot/docs/current/reference/html/production-ready-features.html#production-ready-metrics[Spring Boot reference documentation on metrics] for built-in Spring Boot support after Spring Boot 1.5.

[[installing]]
== Installing
Micrometer provides a legacy bridge to Spring Boot 1.5.
The following example shows the required dependency in Gradle:

[source,groovy,subs=+attributes]
----
implementation 'io.micrometer:micrometer-spring-legacy:latest.release'
----

The following example shows the required dependency in Maven:

[source,xml,subs=+attributes]
----
<dependency>
  <groupId>io.micrometer</groupId>
  <artifactId>micrometer-spring-legacy</artifactId>
  <version>${micrometer.version}</version>
</dependency>
----

You should add this dependency alongside any registry implementations you want to use, such as `micrometer-registry-prometheus`.

[[configuring]]
== Configuring


[[web-monitoring]]
== Web monitoring


[[scheduling]]
== Scheduling


[[cache-monitoring]]
== Cache monitoring


[[data-source-monitoring]]
== Data source monitoring


[[registering-custom-metrics]]
== Registering custom metrics
To register custom metrics, you can inject a `MeterRegistry` into your component:

[source,java,indent=0]
----
class Dictionary {
	private List<String> words = new CopyOnWriteArrayList<>();

	public MyComponent(MeterRegistry registry) {
		registry.gaugeCollectionSize("dictionary.size", Tags.empty(), words);
	}

	...
}
----

If you find that you repeatedly instrument a suite of metrics across components or
applications, you can encapsulate this suite in a `MeterBinder` implementation. By
default, metrics from all `MeterBinder` beans are automatically bound to
the Spring-managed `MeterRegistry`.

[[customizing-individual-metrics]]
== Customizing individual metrics


[[with-spring-boot-actuator]]
== With Spring Boot Actuator


[[application-properties]]
== Application properties

